id: ID356EC26
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-05-27T19:05:36.792733'
last_modified: '2022-05-27T19:05:36.792746'
parser: null
source_metadata:
  title: 'MSV 6,08: Kathāvastu'
  language: bo
  base:
    fFCC6:
      title: Kathāvastu
      base_file: fFCC6.txt
      order: 1
  chapter_to_tile: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
